<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Libro[

<!ELEMENT Libro (Titulo, Seccion, SubSeccion?, Contenido, Copyright)>
<!ATTLIST Libro Catalogo CDATA #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Seccion (#PCDATA)>
<!ELEMENT SubSeccion (#PCDATA)>
<!ELEMENT Contenido ((Capitulo+)|(Capitulo+, Separacion?)+)>
<!ELEMENT Capitulo (Tema+)>
<!ATTLIST Capitulo materia (XML|XHTML) "XML">
<!ELEMENT Tema (#PCDATA)>
<!ELEMENT Separacion EMPTY>
<!ELEMENT Copyright (#PCDATA)>


]>



<Libro Catalogo="HOLA">
    <Titulo> LOS GNOMOS </Titulo>
    <Seccion> 13 </Seccion>
    <SubSeccion> 13.3 </SubSeccion>
    <Contenido>
         <Copyright>Reservado por mi abuela Antonia</Copyright>
            <capitulo materia="XML">
                <Tema>Los muertos a caballo de filipino</Tema>
                <Separacion></Separacion>
            </capitulo>
            <capitulo materia="XHTML">
                <Tema>Los muertos a caballo de filipino</Tema>
            </capitulo>

     </Contenido>

</Libro>